=== neutrons/drtsans/drtsans/configuration/schema/BIOSANS.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "type": "object",
  "properties": {
    "schemaStamp": {"$ref": "common.json#/schemaStamp"},
    "instrumentName": {
      "$ref": "common.json#/instrumentName",
      "default": "BIOSANS"
    },
    "iptsNumber":            {"$ref":  "common.json#/iptsNumber"},
    "dataDirectories":  {"$ref":  "common.json#/dataDirectories"},
    "sample":{
      "type": "object",
      "properties" : {
        "runNumber": {"$ref": "common.json#/sample/properties/runNumber"},
        "thickness": {"$ref": "common.json#/sample/properties/thickness", "default": 1.0},
        "transmission": {"$ref":  "common.json#/sample/properties/transmission"}
      },
      "maxProperties": 3,
      "required": ["runNumber", "thickness", "transmission"]
    },
    "background":        {"$ref":  "common.json#/background"},
    "emptyTransmission": {"$ref":  "common.json#/emptyTransmission"},
    "beamCenter":        {"$ref":  "common.json#/beamCenter"},
    "outputFileName":    {"$ref":  "common.json#/outputFileName"},

    "configuration": {
      "type": "object",
      "properties": {

        "outputDir": {"$ref":  "common.json#/configuration/outputDir"},

        "wavelength":       {"$ref":  "common.json#/configuration/wavelength"},
        "wavelengthSpread": {"$ref":  "common.json#/configuration/wavelengthSpread"},

        "useTimeSlice":         {"$ref":  "common.json#/configuration/useTimeSlice", "default": false},
        "useTimeSliceTransmission": {"$ref":  "common.json#/configuration/useTimeSlice", "default": false},
        "timeSliceInterval": {"$ref":  "common.json#/configuration/timeSliceInterval"},

        "useLogSlice":         {"$ref":  "common.json#/configuration/useLogSlice", "default": false},
        "logSliceName":     {"$ref":  "common.json#/configuration/logSliceName"},
        "logSliceInterval": {"$ref":  "common.json#/configuration/logSliceInterval"},

        "sampleOffset":     {"$ref":  "common.json#/configuration/sampleOffset"},
        "sampleApertureSize":     {"$ref":  "common.json#/configuration/sampleApertureSize"},
        "sampleDetectorDistance": {"$ref":  "common.json#/configuration/sampleDetectorDistance"},
        "sampleToSi":             {"$ref":  "common.json#/definitions/safeStringPositiveFloat"},
        "sourceApertureDiameter": {
          "$ref":  "common.json#/configuration/sourceApertureDiameter",
          "description": "Source aperture diameter (mm)"
        },

        "usePixelCalibration": {"$ref":  "common.json#/configuration/usePixelCalibration", "default": false},

        "maskFileName":     {"$ref":  "common.json#/configuration/maskFileName"},
        "useDefaultMask":   {"$ref":  "common.json#/configuration/useDefaultMask", "default": true,
                             "useEntry": "#configuration/defaultMask"},
        "defaultMask": {"$ref":  "common.json#/configuration/defaultMask",
                        "default": [{"Pixel": "1-18,239-256"}, {"Bank": "18-24,42-48"}]},
        "useMaskBackTubes": {"$ref":  "common.json#/configuration/useMaskBackTubes", "default": false},
        "hasMidrangeDetector": {"type":  "boolean", "default": true},
        "darkMainFileName":    {"$ref":  "common.json#/configuration/darkFileName"},
        "darkWingFileName":    {"$ref":  "common.json#/configuration/darkFileName"},
        "darkMidrangeFileName":    {"$ref":  "common.json#/configuration/darkFileName"},
        "normalization": {"$ref":  "common.json#/configuration/normalization", "default": "Monitor"},
        "normalizationResortToTime":  {"$ref":  "common.json#/configuration/normalizationResortToTime", "default": false},
        "sensitivityMainFileName":    {"$ref": "common.json#/configuration/sensitivityFileName"},
        "sensitivityWingFileName":    {"$ref": "common.json#/configuration/sensitivityFileName"},
        "sensitivityMidrangeFileName":    {"$ref": "common.json#/configuration/sensitivityFileName"},
        "useSolidAngleCorrection":    {"$ref": "common.json#/configuration/useSolidAngleCorrection", "default": true},
        "blockedBeamRunNumber":        {"$ref": "common.json#/configuration/blockedBeamRunNumber"},
        "useThetaDepTransCorrection": {"$ref": "common.json#/configuration/useThetaDepTransCorrection", "default": true},
        "DBScalingBeamRadius":    {"$ref":  "common.json#/configuration/DBScalingBeamRadius", "default": 40.0},
        "mmRadiusForTransmission":    {"$ref": "common.json#/configuration/mmRadiusForTransmission"},
        "absoluteScaleMethod":        {"$ref": "common.json#/configuration/absoluteScaleMethod", "default": "standard"},
        "StandardAbsoluteScale":        {"$ref": "common.json#/configuration/StandardAbsoluteScale", "default": 2.17e-10},

        "numMainQxQyBins":      {"$ref":  "common.json#/configuration/numQxQyBins"},
        "numWingQxQyBins":      {"$ref":  "common.json#/configuration/numQxQyBins"},
        "numMidrangeQxQyBins":      {"$ref":  "common.json#/configuration/numQxQyBins"},
        "1DQbinType":           {"$ref":  "common.json#/configuration/1DQbinType", "default": "wedge"},
        "QbinType":             {"$ref":  "common.json#/configuration/QbinType"},
        "numMainQBins": {
          "$ref":  "common.json#/configuration/numQBins",
          "evaluateCondition": "('{#configuration/QbinType}' == 'linear' and {this} is not None) or ('{#configuration/QbinType}' == 'log' and (({this} is None) ^ ({#configuration/LogQBinsPerDecadeMain} is None)))"
        },
        "numWingQBins": {
          "$ref":  "common.json#/configuration/numQBins",
          "evaluateCondition": "('{#configuration/QbinType}' == 'linear' and {this} is not None) or ('{#configuration/QbinType}' == 'log' and (({this} is None) ^ ({#configuration/LogQBinsPerDecadeWing} is None)))"
        },
        "numMidrangeQBins": {
          "$ref":  "common.json#/configuration/numQBins",
          "evaluateCondition": "('{#configuration/QbinType}' == 'linear' and {this} is not None) or ('{#configuration/QbinType}' == 'log' and (({this} is None) ^ ({#configuration/LogQBinsPerDecadeMidrange} is None)))"
        },
        "LogQBinsPerDecadeMain": {"$ref":  "common.json#/configuration/LogQBinsPerDecade"},
        "LogQBinsPerDecadeWing": {"$ref":  "common.json#/configuration/LogQBinsPerDecade"},
        "LogQBinsPerDecadeMidrange": {"$ref":  "common.json#/configuration/LogQBinsPerDecade"},
        "useLogQBinsDecadeCenter": {"$ref":  "common.json#/configuration/useLogQBinsDecadeCenter", "default": false},
        "useLogQBinsEvenDecade":   {"$ref":  "common.json#/configuration/useLogQBinsEvenDecade", "default": false},

        "WedgeMinAngles":            {"$ref":  "common.json#/configuration/WedgeMinAngles", "default": [-45, 165]},
        "WedgeMaxAngles":            {"$ref":  "common.json#/configuration/WedgeMaxAngles", "default": [45, 190]},
        "autoWedgeQmin":             {"$ref":  "common.json#/configuration/autoWedgeQmin", "default":  0.003},
        "autoWedgeQmax":             {"$ref":  "common.json#/configuration/autoWedgeQmax", "default":  0.04},
        "autoWedgeQdelta":           {"$ref":  "common.json#/configuration/autoWedgeQdelta", "default":  0.01},
        "autoWedgeAzimuthalDelta":  {"$ref":  "common.json#/configuration/autoWedgeAzimuthalDelta", "default": 1.0},
        "autoWedgePeakWidth":        {"$ref":  "common.json#/configuration/autoWedgePeakWidth", "default":  0.25},
        "autoWedgeBackgroundWidth":  {"$ref":  "common.json#/configuration/autoWedgeBackgroundWidth", "default": 1.5},
        "autoWedgeSignalToNoiseMin": {"$ref":  "common.json#/configuration/autoWedgeSignalToNoiseMin", "default": 2.0},
        "AnnularAngleBin":           {"$ref":  "common.json#/configuration/AnnularAngleBin", "default": 1},

        "useErrorWeighting":  {"$ref":  "common.json#/configuration/useErrorWeighting", "default": false},
        "smearingPixelSizeX": {"$ref":  "common.json#/configuration/smearingPixelSizeX"},
        "smearingPixelSizeY": {"$ref":  "common.json#/configuration/smearingPixelSizeY"},
        "useSubpixels":       {"$ref":  "common.json#/configuration/useSubpixels", "default": false},
        "subpixelsX":         {"$ref":  "common.json#/configuration/subpixelsX"},
        "subpixelsY":         {"$ref":  "common.json#/configuration/subpixelsY"},
        "QminMain": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.02,
          "pairedTo": "#configuration/QmaxMain",
          "lessThan": "#configuration/QmaxMain",
          "description": "The minimum |Q| value for scalar, wedge, or annular binning in the main detector"
        },
        "QmaxMain": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.125,
          "pairedTo": "#configuration/QminMain",
          "description": "The maximum |Q| value for scalar, wedge, or annular binning in the main detector"
        },
        "QminWing": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.06,
          "pairedTo": "#configuration/QmaxWing",
          "lessThan": "#configuration/QmaxWing",
          "description": "The minimum |Q| value for scalar, wedge, or annular binning in the wing detector"
        },
        "QmaxWing": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 1.0,
          "pairedTo": "#configuration/QminWing",
          "description": "The maximum |Q| value for scalar, wedge, or annular binning in the wing detector"
        },
        "QminMidrange": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.06,
          "pairedTo": "#configuration/QmaxMidrange",
          "lessThan": "#configuration/QmaxMidrange",
          "description": "The minimum |Q| value for scalar, wedge, or annular binning in the midrange detector"
        },
        "QmaxMidrange": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 1.0,
          "pairedTo": "#configuration/QminMidrange",
          "description": "The maximum |Q| value for scalar, wedge, or annular binning in the midrange detector"
        },
        "overlapStitchIncludeMidrange": {
          "type":  "boolean",
          "description": "If True, the combined I(q) will stitch the main detector to the midrange detector and the midrange detector to the wing detector. If False, the combined I(q) will not include the midrange detector.",
          "default": true
        },
        "overlapStitchQmin": {
          "$ref":  "common.json#/definitions/safeStitchQboundsSpecs",
          "description": "The minimum |Q| value in the region where intensities for detectors overlap",
          "evaluateCondition": "({this} is None) or ({#configuration/overlapStitchIncludeMidrange} == False and len({this}) == 1) or ({#configuration/overlapStitchIncludeMidrange} == True and len({this}) == 2)",
          "pairwiseLessThan": "#configuration/overlapStitchQmax"
        },
        "overlapStitchQmax": {
          "$ref":  "common.json#/definitions/safeStitchQboundsSpecs",
          "evaluateCondition": "({this} is None) or ({#configuration/overlapStitchIncludeMidrange} == False and len({this}) == 1) or ({#configuration/overlapStitchIncludeMidrange} == True and len({this}) == 2)",
          "description": "The maximum |Q| value in the region where intensities for detectors overlap"
        },

        "wedge1QminMain": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.02,
          "lessThan": "#configuration/wedge1QmaxMain"
        },
        "wedge1QmaxMain": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.09,
          "pairedTo": "#configuration/wedge1QminMain"
        },

        "wedge1QminWing": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.08,
          "lessThan": "#configuration/wedge1QmaxWing"
        },
        "wedge1QmaxWing": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.09,
          "pairedTo": "#configuration/wedge1QminWing"
        },

        "wedge1QminMidrange": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.08,
          "lessThan": "#configuration/wedge1QmaxWing"
        },
        "wedge1QmaxMidrange": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.09,
          "pairedTo": "#configuration/wedge1QminWing"
        },

        "wedge1overlapStitchQmin": {
          "$ref":  "common.json#/definitions/safeStitchQboundsSpecs",
          "evaluateCondition": "({this} is None) or ({#configuration/overlapStitchIncludeMidrange} == False and len({this}) == 1) or ({#configuration/overlapStitchIncludeMidrange} == True and len({this}) == 2)",
          "pairwiseLessThan": "#configuration/wedge1overlapStitchQmax"
        },
        "wedge1overlapStitchQmax": {
          "$ref":  "common.json#/definitions/safeStitchQboundsSpecs",
          "evaluateCondition": "({this} is None) or ({#configuration/overlapStitchIncludeMidrange} == False and len({this}) == 1) or ({#configuration/overlapStitchIncludeMidrange} == True and len({this}) == 2)"
        },

        "wedge2QminMain": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.02,
          "lessThan": "#configuration/wedge2QmaxMain"
        },
        "wedge2QmaxMain": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.125,
          "pairedTo": "#configuration/wedge2QminMain"
        },

        "wedge2QminWing": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.06,
          "lessThan": "#configuration/wedge2QmaxWing"
        },
        "wedge2QmaxWing": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 1.0,
          "pairedTo": "#configuration/wedge2QminWing"
        },

        "wedge2QminMidrange": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 0.06,
          "lessThan": "#configuration/wedge2QmaxMidrange"
        },
        "wedge2QmaxMidrange": {
          "$ref":  "common.json#/definitions/safeStringPositiveFloat",
          "default": 1.0,
          "pairedTo": "#configuration/wedge2QminMidrange"
        },

        "wedge2overlapStitchQmin": {
          "$ref":  "common.json#/definitions/safeStitchQboundsSpecs",
          "evaluateCondition": "({this} is None) or ({#configuration/overlapStitchIncludeMidrange} == False and len({this}) == 1) or ({#configuration/overlapStitchIncludeMidrange} == True and len({this}) == 2)",
          "pairwiseLessThan": "#configuration/wedge2overlapStitchQmax"
        },
        "wedge2overlapStitchQmax": {
          "$ref":  "common.json#/definitions/safeStitchQboundsSpecs",
          "evaluateCondition": "({this} is None) or ({#configuration/overlapStitchIncludeMidrange} == False and len({this}) == 1) or ({#configuration/overlapStitchIncludeMidrange} == True and len({this}) == 2)"
        }
      },

      "maxProperties": 89,
      "required": ["outputDir", "wavelength", "wavelengthSpread", "useTimeSlice", "useTimeSliceTransmission",
        "timeSliceInterval", "useLogSlice", "logSliceName", "logSliceInterval", "sampleOffset", "sampleApertureSize",
        "sampleDetectorDistance", "sourceApertureDiameter", "usePixelCalibration", "maskFileName", "useDefaultMask",
        "defaultMask", "useMaskBackTubes", "darkMainFileName", "darkWingFileName", "darkMidrangeFileName",
        "normalization", "normalizationResortToTime", "sensitivityMainFileName", "sensitivityWingFileName",
        "sensitivityMidrangeFileName", "useSolidAngleCorrection", "blockedBeamRunNumber", "useThetaDepTransCorrection",
        "DBScalingBeamRadius", "mmRadiusForTransmission", "absoluteScaleMethod", "StandardAbsoluteScale",
        "numMainQxQyBins", "numWingQxQyBins", "numMidrangeQxQyBins", "1DQbinType", "QbinType", "numMainQBins",
        "numWingQBins", "numMidrangeQBins", "LogQBinsPerDecadeMain", "LogQBinsPerDecadeWing",
        "LogQBinsPerDecadeMidrange", "useLogQBinsDecadeCenter", "useLogQBinsEvenDecade", "WedgeMinAngles",
        "WedgeMaxAngles", "autoWedgeQmin", "autoWedgeQmax", "autoWedgeQdelta", "autoWedgeAzimuthalDelta",
        "autoWedgePeakWidth", "autoWedgeBackgroundWidth", "autoWedgeSignalToNoiseMin", "AnnularAngleBin",
        "useErrorWeighting", "smearingPixelSizeX", "smearingPixelSizeY", "useSubpixels", "subpixelsX", "subpixelsY",
        "sampleToSi", "QminMain", "QmaxMain", "QminWing", "QmaxWing", "QminMidrange", "QmaxMidrange",
        "overlapStitchQmin", "overlapStitchQmax", "overlapStitchIncludeMidrange", "wedge1QminMain", "wedge1QmaxMain",
        "wedge1QminWing", "wedge1QmaxWing", "wedge1QminMidrange", "wedge1QmaxMidrange", "wedge1overlapStitchQmin",
        "wedge1overlapStitchQmax", "wedge2QminMain", "wedge2QmaxMain", "wedge2QminWing", "wedge2QmaxWing",
        "wedge2QminMidrange", "wedge2QmaxMidrange", "wedge2overlapStitchQmin", "wedge2overlapStitchQmax"]
    }
  },
  "maxProperties": 10,
  "required": ["schemaStamp", "instrumentName", "iptsNumber", "dataDirectories", "sample", "background",
    "emptyTransmission", "beamCenter", "outputFileName", "configuration"]
}

=== neutrons/drtsans/scripts/biosans_wedge_reduction.json
{
  "schemaStamp": "2020-04-15T21:09:52.745905",
  "instrumentName": "BIOSANS",
  "iptsNumber": "23782",
  "dataDirectories": null,
  "sample": {
    "runNumber": "4822",
    "thickness": "0.1",
    "transmission": {
      "runNumber": "4822",
      "value": ""
    }
  },
  "background": {
    "runNumber": "4821",
    "transmission": {
      "runNumber": "4821",
      "value": ""
    }
  },
  "emptyTransmission": {
    "runNumber": "4820",
    "value": null
  },
  "beamCenter": {
    "runNumber": "4819"
  },
  "outputFileName": "CG3_4822_wedge",
  "configuration": {
    "outputDir": "/tmp/CG3_4822_wedge",
    "wavelength": "",
    "wavelengthSpread": "",
    "useTimeSlice": false,
    "useTimeSliceTransmission": false,
    "timeSliceInterval": "",
    "useLogSlice": false,
    "logSliceName": "",
    "logSliceInterval": "",
    "sampleOffset": "",
    "sampleApertureSize": "12",
    "sampleDetectorDistance": null,
    "sampleToSi": null,
    "sourceApertureDiameter": "",
    "usePixelCalibration": false,
    "maskFileName": "",
    "useDefaultMask": true,
    "defaultMask": [
      "{'Pixel':'1-18,239-256'}",
      "{'Bank':'18-24,42-48'}"
    ],
    "useMaskBackTubes": false,
    "darkMainFileName": "/HFIR/CG3/shared/Cycle486/CG3_5187.nxs.h5",
    "darkWingFileName": "/HFIR/CG3/shared/Cycle486/CG3_5187.nxs.h5",
    "darkMidrangeFileName": "/HFIR/CG3/shared/Cycle486/CG3_5187.nxs.h5",
    "normalizationResortToTime": false,
    "normalization": "Monitor",
    "sensitivityMainFileName": "/HFIR/CG3/shared/Cycle486/Old_Sens/sens_f4829m7p0_TDC_SAC.h5",
    "sensitivityWingFileName": "/HFIR/CG3/shared/Cycle486/Old_Sens/sens_f4843w1p4_TDC_SAC.h5",
    "sensitivityMidrangeFileName": "/HFIR/CG3/shared/Cycle486/Old_Sens/sens_f4843w1p4_TDC_SAC.h5",
    "useSolidAngleCorrection": true,
    "blockedBeamRunNumber": "",
    "useThetaDepTransCorrection": true,
    "DBScalingBeamRadius": "",
    "mmRadiusForTransmission": "",
    "absoluteScaleMethod": "standard",
    "StandardAbsoluteScale": "2e-8",
    "numMainQxQyBins": 150,
    "numWingQxQyBins": 150,
    "numMidrangeQxQyBins": 150,
    "1DQbinType": "wedge",
    "QbinType": "log",
    "numMainQBins": 33,
    "numWingQBins": 33,
    "numMidrangeQBins": 33,
    "LogQBinsPerDecadeMain": null,
    "LogQBinsPerDecadeWing": null,
    "LogQBinsPerDecadeMidrange": null,
    "useLogQBinsDecadeCenter": false,
    "useLogQBinsEvenDecade": false,
    "WedgeMinAngles": [
      -30,
      60
    ],
    "WedgeMaxAngles": [
      30,
      120
    ],
    "autoWedgeQmin": 0.003,
    "autoWedgeQmax": 0.04,
    "autoWedgeQdelta": 0.01,
    "autoWedgeAzimuthalDelta": 1,
    "autoWedgePeakWidth": 0.25,
    "autoWedgeBackgroundWidth": 1.5,
    "autoWedgeSignalToNoiseMin": 2,
    "AnnularAngleBin": "1",
    "useErrorWeighting": true,
    "smearingPixelSizeX": null,
    "smearingPixelSizeY": null,
    "useSubpixels": false,
    "subpixelsX": null,
    "subpixelsY": null,
    "QminMain": "",
    "QmaxMain": "",
    "QminWing": "",
    "QmaxWing": "",
    "QminMidrange": "",
    "QmaxMidrange": "",
    "overlapStitchQmin":  0.031,
    "overlapStitchQmax":  0.0375,
    "wedge1QminMain": 0.02,
    "wedge1QmaxMain": 0.09,
    "wedge1QminWing": 0.08,
    "wedge1QmaxWing": 0.09,
    "wedge1QminMidrange" : 0.04,
    "wedge1QmaxMidrange" : 0.05,
    "wedge1overlapStitchQmin": 0.0825,
    "wedge1overlapStitchQmax": 0.0875,
    "wedge2QminMain": 0.02,
    "wedge2QmaxMain": 0.125,
    "wedge2QminWing": 0.06,
    "wedge2QmaxWing": 1,
    "wedge2QminMidrange": 0.05,
    "wedge2QmaxMidrange": 0.7,
    "wedge2overlapStitchQmin": 0.075,
    "wedge2overlapStitchQmax": 0.095,
    "overlapStitchIncludeMidrange": false
  }
}
